### ISSUE TITLE
Mock数据的时候，总报：proxy.config.js parse error 15个，是怎么回事？要怎么修改

### ISSUE THREAD

**Issue by zhouylgithub** [dvajs/dva-docs#14]
![image](https://cloud.githubusercontent.com/assets/6264664/18977535/bbbdfe80-86ed-11e6-8e0f-12ad2126cb6d.png)

**Comment by sorrycc** [comment]
proxy.config.js 解析出错了，检查下语法看。

**Comment by nikogu** [comment]
@zhouylgithub `proxy.config.json` 顶部需要添加 `use strick;`

**Comment by ouzhou** [comment]
@sorrycc 我也是这个问题 跑的你的那个教程的步骤，proxy.config.js 用的是dva自己生成，mock文件夹的users.js是copy教程的代码

**Comment by sorrycc** [comment]
升级 dora-plugin-proxy 到 0.8.4，会提示出错原因了。

![image](https://cloud.githubusercontent.com/assets/35128/19011607/4ba01b42-87ce-11e6-8018-eb34ec700718.png)

**Comment by sorrycc** [comment]
有问题再 reopen 。

**Comment by ohmyauthentic** [comment]
"dora-plugin-proxy": "0.8.4",这样好像没有提示错误信息

**Comment by dangyanglim** [comment]
@nikogu 有加了，这个问题怎么处理，我的也有

**Comment by dangyanglim** [comment]
![1](https://cloud.githubusercontent.com/assets/16640185/19584974/21ebd734-977b-11e6-925c-4b3b978d0b73.png)

**Comment by nikogu** [comment]
![image](https://cloud.githubusercontent.com/assets/1179603/19585055/dce29050-977b-11e6-85b4-e4ee39a51405.png)

这里吧

**Comment by dangyanglim** [comment]
https://github.com/dangyanglim/dva-start.git
@nikogu 还是不行，我源码在上面
