### ISSUE TITLE
组件申明

### ISSUE THREAD

**Issue by ohmyauthentic** [dvajs/dva-docs#18]
文档5 中建议使用第三种方式，ant design组件API上面都是用的第一种方式，如何使用第三种方式使用ant官方组件

**Comment by nikogu** [comment]
antd官网一般是最基础的用法，在真实项目中都是使用es6的语法，所以建议使用第三种，使用方式也是一样的。https://github.com/dvajs/dva/blob/master/examples/user-dashboard/src/components/Users/UserList.jsx#L39

**Comment by ohmyauthentic** [comment]
比如我使用From，LoginForm = Form.create()(LoginForm);需要加这句吗？改成第三种方法后找不到 this.props.form;属性

**Comment by nikogu** [comment]
props可以通过参数获取，https://github.com/dvajs/dva/blob/master/examples/user-dashboard/src/components/Users/UserList.jsx#L39，例如：

```

let LoginForm = ({ form }) => { console.log(form); return <div></div>};
LoginForm = Form.create()(LoginForm);

```

**Comment by ohmyauthentic** [comment]
@nikogu 可以了，谢谢，但感觉LoginForm = Form.create()(LoginForm);这种写法好hack
