### ISSUE TITLE
Users 模块命名在教程里没有统一

### ISSUE THREAD

**Issue by junmaqiang** [dvajs/dva-docs#26]
`https://github.com/dvajs/dva-docs/blob/master/v1/zh-cn/tutorial/05-组件设计实践.md`
上面这个地址里面，提到了 User.jsx  ，Users.jsx  , Users.js   搞晕了。
有地方是错误的！

**Comment by nikogu** [comment]
@junmaqiang 请详细描述下呢

**Comment by junmaqiang** [comment]
`设置路由

在准备好了 dva 的基本框架以后，需要为我们的项目配置一下路由，这里首先设置 Users Router Container 的访问路径，并且在 /routes/ 下创建我们的组件文件 User.jsx。`
你看，上面就要求创建 User.jsx

但是下面代码中 路由设置 这里写的又是Users,  
`// .src/router.js
import React, { PropTypes } from 'react';
import { Router, Route } from 'dva/router';
import Users from './routes/Users';

export default function({ history }) {
  return (
    <Router history={history}>
      <Route path="/users" component={Users} />
    </Router>
  );
};`

**Comment by nikogu** [comment]
@junmaqiang ...这里可以简写不带后缀哈，这个是webpack里面的内容，建议有空可以看看

**Comment by junmaqiang** [comment]
后缀我晓得，我这边不好截图，否则我就上图来表明我的问题了哈哈！
User   和  Users  不是一个东东呢，兄弟！
