### ISSUE TITLE
用于生产环境的webpack.config

### ISSUE THREAD

**Issue by sa6** [dvajs/dva-docs#28]
能不能提供一个用于生产环境的webpack.config呢？
"build": "atool-build",
这样build的文件实在是太大了
一个小demo就上兆的级别了

**Comment by nikogu** [comment]
因为本身的依赖就很多，react，redux，sagas，还有babel编译过后的代码，等，如果你用了antd可以使用antd的babel插件，会小一点

**Comment by sa6** [comment]
@nikogu 那这个问题要怎么解决的呢？一个小demo的index.js就上兆的级别了。
比如把react.min.js单独出来一个文件不要去打包他，按需加载等等。这些是否配置一个webpack就能解决呢？

**Comment by nikogu** [comment]
配置 webpack 也解决不了吧，就像我说的，你的依赖本身就有那么多，所以如果你确实很关心大小，你可以考虑只用纯react，或者把项目使用更小的 vue 等框架使用

**Comment by iwege** [comment]
atool-build 可以指定config文件。参见https://github.com/ant-tool/atool-build
其他的就需要配置webpack来做了。
