### ISSUE TITLE
关于mapStateToProps

### ISSUE THREAD

**Issue by cao2028196** [dvajs/dva-docs#30]
文档里解释 
// 指定订阅数据，这里关联了 users
function mapStateToProps({ users }) {
  return {users};
}
mapStateToProps怎么就关联了数据， users 哪里来的？怎么找到对应路劲？

**Comment by nikogu** [comment]
重点是这个方法的掉用，谁调用了它，谁就给它穿参数，获取它的值，对吧

**Comment by nikogu** [comment]
https://github.com/dvajs/dva/blob/master/examples/user-dashboard/src/routes/Users.jsx#L107

**Comment by junmaqiang** [comment]
我也很纳闷，这个users到底是models下面的users，还是routes下的users

**Comment by nikogu** [comment]
mapStateToProps 方法里面的都是 model

**Comment by cao2028196** [comment]
users  应该指的是 models/users.js 里面的 “namespace”

**Comment by hanguolong1989** [comment]
@cao2028196 说得对，就是models里面的namespace
