### ISSUE TITLE
提问：重命名 model 的名字

### ISSUE THREAD

**Issue by soulmachine** [dvajs/dva-docs#31]
这个不是个bug, 只是一个提问，也许开个 issue 不太合适，不过暂时偷懒就在这里提问吧。

我想尝试给 model 重命名，在这个例子[DVA 快速上手](https://github.com/dvajs/dva-docs/blob/master/v1/zh-cn/getting-started.md) 里，我把index.js的两行代码修改了一下：

* `namespace: 'count',` 改为 `namespace: 'countxxx',`
* mapStateToProps()这个函数改了一行，

        function mapStateToProps(state) {
          return { count: state.countxxx };
        }

这时候在 redux-devtools 里面，已经看到state里有 `countxxx`了，但是点击按钮，state不会改变，我应该是漏了一步，请教一下还需要做哪些才能够把model重命名？

**Comment by sorrycc** [comment]
全文搜索下，`dispatch({ type: 'count/abc' })` 的 `count` 也要改下。

**Comment by soulmachine** [comment]
@sorrycc 可以了！感谢大牛！原来namespace相当于是state和reducers的前缀，想想也挺合理
