### ISSUE TITLE
在例子中没有找到commonjs文件配置的位置

### ISSUE THREAD

**Issue by sevennights** [dvajs/dva-docs#32]
如题 木有找到这个common.js文件的配置位置在哪里 
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Demo</title>
  <link rel="stylesheet" href="index.css" />
</head>
<body>

<div id="root"></div>

<script src="common.js"></script>
<script src="index.js"></script>

</body>
</html>

**Comment by sorrycc** [comment]
https://github.com/ant-tool/atool-build/blob/9baca94/src/getWebpackCommonConfig.js#L182
默认是提取 common.js 的。
