### ISSUE TITLE
封装request.js跨域请求数据

### ISSUE THREAD

**Issue by wm3445** [dvajs/dva-docs#38]
export async function changeCheckCode(params) {

  return request(`http://192.168.0.107:8080/test/api/captcha`, {
    method: "get",
    mode: "no-cors",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded"
    }
  });
}
浏览器返回状态 200 能接收到数据

此方法返回错误  Error at checkStatus (webpack:///./src/utils/request.js?:23:15)

**Comment by sorrycc** [comment]
重复了，https://github.com/dvajs/dva-cli/issues/26
