### ISSUE TITLE
根据指引到了--添加Reducers，这里不能正常显示UserList

### ISSUE THREAD

**Issue by golden-hu** [dvajs/dva-docs#4]
dva-docs/zh/tutorial/06-添加Reducers
根据这个指引，一步一步跟着实现时。完成之后访问localhost:8989/#/users显示的页面是个空白页面

-- users.js
`import { hashHistory } from 'dva/router';

export default {
    namespace : 'users',
    state:{
        list:[],
        total:null,
        loading:false,//控制加载状态
        current:null,//当前分页信息
        currentItem:{},//当前操作的用户对象
        modalVisible:false,//弹出窗的显示状态
        modalType:'create',//弹出窗的类型（添加用户，编辑用户）
    },

    subscriptions: {
        setup({ dispatch, history }) {
            history.listen(location => {
                if(location.pathname === '/users'){
                    dispatch({
                        type:'querySuccess',
                        payload:{}
                    });
                }
            });
        },
    },
    effects:{
        *query(){},
        *create(){},
        *'delete'(){},
        *update(){},
    },
    reducers:{
        showLoading(){},//控制加载状态的reducer
        showModal(){},//控制modal显示状态的reducer
        hideModal(){},
        querySuccess(){
            const mock = {
                total:3,
                current:1,
                loading:false,
                list:[
                    {
                        name: '张三',
                        age: 23,
                        address: '成都',
                    },
                    {
                        name: '李四',
                        age: 24,
                        address: '杭州',
                    },
                    {
                        name: '王五',
                        age: 25,
                        address: '上海',
                    },
                ],
            };
            return {...state, ...mock, loading:false};
        },
        createSuccess(){},
        deleteSuccess(){},
        updateSuccess(){},
    }
}`

--'router/Users.jsx'
`import React,{ Component,PropTypes } from 'react';

import { connect } from 'dva';

import UserList from '../components/Users/UserList';
import UserSearch from '../components/Users/UserSearch';
import UserModal from '../components/Users/UserModal';

import styles from './Users.less';

function Users({location,dispatch,users }) {
    const {
        list,
        total,
        loading,//控制加载状态
        current,//当前分页信息
        currentItem,//当前操作的用户对象
        modalVisible,//弹出窗的显示状态
        modalType
    } = users;

    const userSearchProps = {};
    const userListProps = {
        dataSource:list,
        total,
        loading,
        current,
    };
    const userModalProps = {};

    return(
        <div className={styles.normal}>
        {/* 用户筛选搜索框*/}
        <UserSearch {...userSearchProps} />
        {/* 用户信息展示列表 */}
        <UserList {...userListProps} />
        {/* 添加用户 & 修改用户弹出浮层 */}
        <UserModal {...userModalProps} />
        </div>
    );
}

Users.propTypes = {
    users: PropTypes.object,
}

//指定订阅数据，这里关联了users
function mapStateToProps({ users }){
    return {users};
}
//建立数据关联关系
export default connect(mapStateToProps)(Users);`

**Comment by sorrycc** [comment]
维护文档的同学休假了，有啥报错吗?
