### ISSUE TITLE
组件实践 - 实验失败

### ISSUE THREAD

**Issue by kimoziiiii** [dvajs/dva-docs#41]
现在如果你的本地环境是成功的，访问 http://127.0.0.1:8989/#/users 浏览器中看到

做到这步后，刷新页面显示为空 ，检查了2遍代码，也没有异常发生。
----------------------------
测试环境：
window7 64位

**Comment by sorrycc** [comment]
检查控制台和 chrome devtool，看下日志。

**Comment by kimoziiiii** [comment]
:) 解决了 非常感谢。
