### ISSUE TITLE
npm run build多页面构建

### ISSUE THREAD

**Issue by sexyios** [dvajs/dva-docs#43]
请教个问题，dva怎么配置多页面打包webpack配置，dva框架里的webpack是安装脚手架之后自动生成的，但是这样无法达成需求，build之后怎样构建成多页面的，请问有什么好的提示或者对应的案例参考下吗？
![y 6wi iw t usv 6g2 epq](https://cloud.githubusercontent.com/assets/8684040/21210519/b7a1e708-c2b6-11e6-9775-cd74b7773b9b.png)效果变成多文件管理这样的

**Comment by sorrycc** [comment]
配多个 webpack 的 entry 就是多页面的了。

**Comment by sorrycc** [comment]
问题请统一到  https://github.com/dvajs/dva/issues 提。
