### ISSUE TITLE
09 mock数据--这里提示proxy: proxy.config.js parse error

### ISSUE THREAD

**Issue by golden-hu** [dvajs/dva-docs#5]
学习到了 mock这一节，根据文章将代码coding进去之后
在终端中提示proxy: proxy.config.js parse error
/mock/users.js
代码如下：

> // ./src/mock/users.js
>'use strict';
>
>const qs = require('qs');
>
>// 引入 mock js
>const mockjs = require('mockjs');
>
>module.exports = {
>  'GET /api/users' (req, res) {
>    const page = qs.parse(req.query);
>
>   const data = mockjs.mock({
>      'data|100': [{
>        'id|+1': 1,
>        name: '@cname',
>        'age|11-99': 1,
>        address: '@region'
>      }],
>      page: {
>        total: 100,
>        current: 1
>      }
>    });
>
>    res.json({
>      success: true,
>     data,
>      page: {
>        current: 1,
>        total: 100,
>      }
>    });
>  },
>};

proxy.config.js代码

> 'use strict';
> 
> const mock = {};
> 
> require('fs').readdirSync(require('path').join(__dirname + '/mock'))
>   .forEach(function (file) {
>     Object.assign(mock, require('./mock/' + file));
>   });
> 
> module.exports = mock;

请问我应该如何修改？

**Comment by sorrycc** [comment]
```
// ./src/mock/users.js
```

这行删掉试试。

**Comment by golden-hu** [comment]
删除之后，重建了/mock/users.js文件，然后从example.js中复制代码，再逐步修改代码之后，没有出现parse error。
我之前已经逐条对比了代码。不知道为什么。
待解。目前这个暂时没有出现了

**Comment by ouzhou** [comment]
@golden-hu  请问你是如何解决的？？？

**Comment by ohmyauthentic** [comment]
@ouzhou 你解决了吗，我也遇到了

**Comment by sorrycc** [comment]
删掉第一行 `// ./src/mock/user.js`，重启 `npm start`。

**Comment by ohmyauthentic** [comment]
删除了之后，重启还是这个错误

**Comment by sorrycc** [comment]
控制台有啥输出没？

**Comment by ohmyauthentic** [comment]
request.js:36 GET http://localhost:8989/api/users? 404 (Not Found)

**Comment by ohmyauthentic** [comment]
request.js:36 GET http://localhost:8989/api/users? 404 (Not Found)

**Comment by sorrycc** [comment]
没提示 `proxy: proxy.config.js parse error` ?

**Comment by ohmyauthentic** [comment]
按那个 golden-hu 的做法，错误没了，现在是找不到http://localhost:8989/api/users? Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by ohmyauthentic** [comment]
'GET /api/users':function (req, res)这样不报错'GET /api/users' (req, res)就报错

**Comment by ohmyauthentic** [comment]
还是报错，我刚刚电脑控制台阻塞住了，没刷出来，还是会报proxy: proxy.config.js parse error

**Comment by ohmyauthentic** [comment]
我用example 测试没问题，然后加了这两句
const qs = require('qs');
const mockjs = require('mockjs');
就开始报错了

**Comment by ohmyauthentic** [comment]
终于解决了，升级自动生成的package.json没有解决问题，然后我用项目里的package.json 替换了自动生成的package.json，然后成功了，是不是每次修改mock下的文件都需要重启啊？

**Comment by sorrycc** [comment]
用 watchDirs 参数，参考这个 commit，https://github.com/dvajs/dva-cli/commit/49b570af172365f2acd5688eda0184133b8d5663 。

**Comment by fanqidaoerxing** [comment]
按着教程敲到这里发现请求不到接口， 控制台提示:
proxy: proxy.config.js parse error: Error: Cannot find module 'mockjs'
查看package.json发现里面确实没有依赖 mockjs，在devDependencies中加入依赖
"mockjs": "^1.0.1-beta3"
重新 npm install 就好了

**Comment by fanqidaoerxing** [comment]
按着教程敲到这里发现请求不到接口， 控制台提示:
`proxy: proxy.config.js parse error: Error: Cannot find module 'mockjs'`
查看package.json发现里面确实没有依赖 mockjs，在devDependencies中加入依赖
`"mockjs": "^1.0.1-beta3"`
重新 npm install 就好了

**Comment by mervynyang** [comment]
为什么我执行`npm i mockjs -S`一直安装不了？
控制台信息：
`loadDep:rc-util: verb afterAdd /Users/air/.npm/graceful-readlink/1.0.1/package/package.json written`

**Comment by fanqidaoerxing** [comment]
➜  user-dashboard npm i mockjs -S
/Users/xxx/Documents/ReactProject/user-dashboard
└── mockjs@1.0.1-beta3



我这里执行时没有问题的，我的node版本3.10.8，另外看看你的package.json所属用户是不是你自己（sudo创建的话，没有权限修改）
这是我遇到的一些问题，希望能对你有所帮助
 
 
------------------ Original ------------------
From: "MervynYang"; 
Date: 2016年11月7日(星期一) 下午3:26
To: "dvajs/dva-docs"; 
Cc: "icremoo"; "Comment"; 
Subject: Re: [dvajs/dva-docs] 09 mock数据--这里提示proxy: proxy.config.js parse error (#5)

 

为什么我执行npm i mockjs -S一直安装不了？
 控制台信息：
 loadDep:rc-util: verb afterAdd /Users/air/.npm/graceful-readlink/1.0.1/package/package.json written

**Comment by fanqidaoerxing** [comment]
@mervynyang 我这边执行是没有问题的，你的node版本是多少？我的是3.10.8
```
➜  user-dashboard npm i mockjs -S
/Users/xxx/Documents/ReactProject/user-dashboard
└── mockjs@1.0.1-beta3
```

**Comment by mervynyang** [comment]
@fanqidaoerxing node是v7.1.0 难道是版本问题吗？？

**Comment by yvanwangl** [comment]
@golden-hu  出现了一样的问题，在终端中提示proxy: proxy.config.js parse error
