### ISSUE TITLE
Router Component -> Route Component

### ISSUE THREAD

**Issue by sorrycc** [dvajs/dva-docs#6]
Router 表示路由表，而 Route 表示单个路由。所以目录上也是：

```
+ routes
- router.js
```

https://github.com/dvajs/dva-docs/blob/master/zh/concepts/01-%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5.md#router-components

**Comment by nikogu** [comment]
好的，我更新一下
