### ISSUE TITLE
请教问题：在model中如何描述继承关系

### ISSUE THREAD

**Issue by windyrain** [dvajs/dva-docs#8]
dva团队的各位大大，你们好：

我在model中如何描述继承关系上有疑问

![vln18 96n d2j6 x hewjh](https://cloud.githubusercontent.com/assets/7961364/18697989/11c7dd9c-7ff9-11e6-93ec-8e1681ecf2f5.png)

我使用的是计数器的例子

app._models中存了一个对象数组，下标为0的是命名空间为：**count** 的对象

如果现在我需要一个正向计数器 也需要一个反向计数器

其实他们仅仅是在 对象的**reducers** 属性中`add` 这个方法的实现不一致

这个时候如果不想重新写一个结构基本一致的对象，应该怎么去完成一个计数器基类

并让正向计数，和反向计数分别实现里面的方法，并添加自有的属性和方法

希望可以得到你们的帮助，万分感谢！

**Comment by nikogu** [comment]
`模块的设计各有各的看法，`

就我来讲，遇到你的问题，首先：

1. modle 不复用
1. 不用继承，多用组合

所以我的方案是：

将 add 等方法抽离 model，抽象成通用的计数器模型，然后你的两个计数器模型里面分别有自己的状态，以及可以调用通用计数器模型的方法

**Comment by windyrain** [comment]
谢谢您的建议！

不过，我想我之前可能有点领会错了model中的js文件的作用了

我又看了以下HackerNews这个例子

我比较关心的地方似乎是在

![image](https://cloud.githubusercontent.com/assets/7961364/18738055/b20acc5c-80ca-11e6-87f2-960e7a7ba4e5.png)

top new show ask job似乎都是新闻的类型

而他们肯定各自有各自的特性，而他们也有各自的实现细节

这些东西，在我目前的观察下，应该是在component中实现的

我应该还没有理解component的职责。

之前我以为component只是单纯的render，但是看起来并不是这么的简单

dva的某篇文章中也讲到了，有通用组件和业务组件之分。

我对于这些东西还在研究阶段，一开始把model理解成类似于后端的DO PO了

非常感谢您的帮助，谢谢！
