### ISSUE TITLE
样式文件引入图片的路径问题

### ISSUE THREAD

**Issue by raisezhang** [dvajs/dva-docs#9]
1、less 引入图片问题
纯的 Component less文件中引用一张图片，按照我之前的开发经验，会在当前目录创建 img 目录，然后在样式文件中『 ./img/a.png』即可，这样可以方便管理图片。 但是在 dva 中引入会提示路径错误，室友相关的脚本将图片全部统一管理了么？ 貌似没有找到相关图片的配置项。 （在 jsx 里面倒是可以通过 import 实现，但是这种方法还是没有样式文件优雅）

2、如何查看 dora 服务的 类 www 目录 

多谢啦  @sorrycc

**Comment by nikogu** [comment]
@raisezhang dva底层用的工具是[atool-build](https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js#L132)，图片访问路径如果没有配 `rootPath`（好像叫这个），是走的相对路径吧，你可以试试

dora 的底层是koa的static，没有累死 www的 目录哦

**Comment by raisezhang** [comment]
1、样式问题

打印了下  `console.log(webpackConfig.module);`
`{ test: /\.(png|jpg|jpeg|gif)(\?v=\d+\.\d+\.\d+)?$/i,
       loader: 'url?limit=10000' },`
没看到有相关 rootPath 的配置。    

你指的相对路径是这样么？ 
![image](https://cloud.githubusercontent.com/assets/1481983/18705183/c020a524-801f-11e6-9d95-88bcf6f40fbf.png)
在 SectionLeft.less 中引入 logo.png   ` background-image:url(./img/logo.png);  `  这样会报路径异常！

2、dora 问题
主要是想知道部署过去的文件是什么结构，文件名有什么变化等   好查问题 （比如图片找不到问题，我就是瞄一眼看看放哪了 -_-）

多谢 @nikogu

**Comment by nikogu** [comment]
@raisezhang 你把你引入的图片的代码发来看看，以及报错的截图

**Comment by raisezhang** [comment]
代码截图：
![image](https://cloud.githubusercontent.com/assets/1481983/18706727/b428b2e2-8025-11e6-988e-79707311af3d.png)

报错信息：
`ERROR in ./src/components/layouts/SectionLeft/SectionLeft.less
Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve module 'img/logo.png' in /Users/src/components/layouts/SectionLeft
    at /Users/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/Users/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Users/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /Users/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /Users/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Users/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /Users/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /Users/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
 @ ./src/components/layouts/SectionLeft/SectionLeft.jsx 41:19-48`

@nikogu   辛苦

**Comment by nikogu** [comment]
@raisezhang 这个问题确实比较复杂，但是解决却很简单，只需要改一下引用路径就好了（当作你是从根目录开始找的，package.json的目录那一层）

```css
.sideLogo {
  background-image: url('../../../../components/layouts/SectionLeft/img/logo.png');
}
```
比如 `user-dashboard` 这个例子，在 `src` 中添加 `img/test.png` 资源，这样可以访问到：

```css
body {
  background: url('../src/img/test.png');
}
```


相关issue：https://github.com/webpack/css-loader/issues/74#issuecomment-110745359

**Comment by nikogu** [comment]
如果想看部署的文件结构，可以 `npm run build` 查看

**Comment by raisezhang** [comment]
如果通过  ../  上级的方式处理的话  在整理 compmonts 的时候是很恶心的...   （移动组件时） 

还有是否可以通过类似 [webpack/css-loader#74](https://github.com/webpack/css-loader/issues/74#issuecomment-221193245)  这种方式集成至 dva 中！

dora的问题，知道了   多谢~   

谢谢 @nikogu  @sorrycc   ^_^

**Comment by raisezhang** [comment]
要么就是不建议这种图片的组织方式， 直接放到 ./src/images  ...   但是会存在找不太好找，删除的话也很费劲

**Comment by nikogu** [comment]
@raisezhang 图片不建议跟着组件走，组件中对图片的引用最好不要有，如果是业务需求统一放在 根目录的 `./src/images` 下面，按照类别可以进行文件夹分类

**Comment by nikogu** [comment]
另外，其实你是可以自定义 `webpack.config.json` 的，对你的业务做定制化

**Comment by raisezhang** [comment]
好的 多谢啦 ~
